site_name: My Docs

## Configuration
theme:
  name: material
##  custom_dir: build/overrides
#  language: zh
##  features:
#
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format