site_name: My Docs

## Configuration
theme:
  name: readthedocs
##  custom_dir: build/overrides
#  language: zh
##  features:
#
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# page tree
nav:
  - My notes:
      - 2024-01: 2024_01_learning.md
      - 2024-02: 2024_02_learning.md