name: Build and deploy mkdocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: install tree
        run: sudo apt-get install -y tree
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
#      - run: pip install mkdocs
      - run: pip install mkdocs-material
#      - run: pwd
#      - run: ls -al
#      - run: ls -al ./docs
#      - working-directory: ./docs
#        run: mkdocs gh-deploy --force
      - run: |
          pwd
          tree .
          mkdocs gh-deploy --force --verbose
          tree .